export const CREATE_USER = "CREATE_USER";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const BEING_API_CALL = "BEING_API_CALL";
